import {
  bigint,
  boolean,
  index,
  integer,
  jsonb,
  numeric,
  pgEnum,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core';

export const repoStatus = pgEnum('repo_status', [
  'OPEN',
  'ACTIVE',
  'REPAID',
  'CANCELLED',
  'EXPIRED',
  'DEFAULTED',
]);

export const v2OfferStatus = pgEnum('v2_offer_status', [
  'OPEN',
  'PARTIALLY_FILLED',
  'FILLED',
  'CANCELLED',
  'EXPIRED',
]);

export const v2PositionStatus = pgEnum('v2_position_status', [
  'ACTIVE',
  'REPAID',
  'AUCTION',
  'LIQUIDATED',
  'AUCTION_FAILED',
  'COLLATERAL_CLAIMED',
]);

export const vaultBucket = pgEnum('vault_bucket', [
  'AVAILABLE',
  'OFFER_RESERVED',
  'POSITION_LOCKED',
  'AUCTION_LOCKED',
  'MARGIN_LOCKED',
]);

export const auctionStatus = pgEnum('auction_status', [
  'OPEN',
  'SETTLED',
  'EXPIRED',
  'COLLATERAL_CLAIMED',
  'CANCELLED',
]);

export const claimStatus = pgEnum('claim_status', ['PENDING', 'CLAIMED', 'CANCELLED']);
export const marginAccountStatus = pgEnum('margin_account_status', [
  'HEALTHY',
  'MARGIN_CALL',
  'LIQUIDATING',
  'LIQUIDATED',
  'AUCTION_FAILED',
  'CLOSED',
]);
export const automationJobStatus = pgEnum('automation_job_status', [
  'PENDING',
  'RUNNING',
  'SUBMITTED',
  'SUCCEEDED',
  'RETRY',
  'DEAD',
  'CANCELLED',
]);

export const assets = pgTable('assets', {
  id: uuid('id').defaultRandom().primaryKey(),
  chainId: integer('chain_id').notNull(),
  address: text('address').notNull(),
  name: text('name').notNull(),
  symbol: text('symbol').notNull(),
  decimals: integer('decimals').notNull(),
  cleanverseRequestId: text('cleanverse_request_id').notNull(),
  cleanverseStatus: text('cleanverse_status').notNull(),
  paused: boolean('paused').notNull().default(false),
  enabled: boolean('enabled').notNull().default(false),
  evidenceHash: text('evidence_hash'),
  valuationHash: text('valuation_hash'),
  metadata: jsonb('metadata').$type<Record<string, unknown>>().notNull().default({}),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  uniqueIndex('assets_chain_address_uidx').on(table.chainId, table.address),
  index('assets_enabled_idx').on(table.enabled),
]);

export const repos = pgTable('repos', {
  id: uuid('id').defaultRandom().primaryKey(),
  chainId: integer('chain_id').notNull(),
  marketAddress: text('market_address').notNull(),
  repoId: numeric('repo_id', { precision: 78, scale: 0 }).notNull(),
  seller: text('seller').notNull(),
  buyer: text('buyer'),
  permittedBuyer: text('permitted_buyer'),
  assetAddress: text('asset_address').notNull(),
  collateralAmount: numeric('collateral_amount', { precision: 78, scale: 0 }).notNull(),
  principalAmount: numeric('principal_amount', { precision: 78, scale: 0 }).notNull(),
  openingFee: numeric('opening_fee', { precision: 78, scale: 0 }),
  repurchaseAmount: numeric('repurchase_amount', { precision: 78, scale: 0 }),
  annualRateBps: integer('annual_rate_bps').notNull(),
  durationSeconds: integer('duration_seconds').notNull(),
  offerExpiry: timestamp('offer_expiry', { withTimezone: true }).notNull(),
  openedAt: timestamp('opened_at', { withTimezone: true }),
  maturityAt: timestamp('maturity_at', { withTimezone: true }),
  graceEndsAt: timestamp('grace_ends_at', { withTimezone: true }),
  closedAt: timestamp('closed_at', { withTimezone: true }),
  valuationHash: text('valuation_hash').notNull(),
  status: repoStatus('status').notNull(),
  createTxHash: text('create_tx_hash').notNull(),
  lastTxHash: text('last_tx_hash').notNull(),
  lastBlockNumber: bigint('last_block_number', { mode: 'bigint' }).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  uniqueIndex('repos_chain_market_repo_uidx').on(table.chainId, table.marketAddress, table.repoId),
  index('repos_status_idx').on(table.status),
  index('repos_seller_idx').on(table.seller),
  index('repos_buyer_idx').on(table.buyer),
  index('repos_asset_idx').on(table.assetAddress),
]);

export const chainEvents = pgTable('chain_events', {
  chainId: integer('chain_id').notNull(),
  txHash: text('tx_hash').notNull(),
  logIndex: integer('log_index').notNull(),
  blockNumber: bigint('block_number', { mode: 'bigint' }).notNull(),
  blockHash: text('block_hash').notNull(),
  contractAddress: text('contract_address').notNull(),
  eventName: text('event_name').notNull(),
  payload: jsonb('payload').$type<Record<string, unknown>>().notNull(),
  deploymentId: uuid('deployment_id'),
  module: text('module').notNull().default('REPO_MARKET'),
  protocolVersion: text('protocol_version').notNull().default('v1'),
  blockTimestamp: timestamp('block_timestamp', { withTimezone: true }),
  finalized: boolean('finalized').notNull().default(true),
  removed: boolean('removed').notNull().default(false),
  observedAt: timestamp('observed_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  primaryKey({ columns: [table.chainId, table.txHash, table.logIndex] }),
  index('chain_events_block_idx').on(table.chainId, table.blockNumber),
  index('chain_events_deployment_block_idx').on(table.deploymentId, table.blockNumber),
]);

export const indexerCheckpoints = pgTable('indexer_checkpoints', {
  chainId: integer('chain_id').notNull(),
  consumer: text('consumer').notNull(),
  blockNumber: bigint('block_number', { mode: 'bigint' }).notNull(),
  blockHash: text('block_hash').notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [primaryKey({ columns: [table.chainId, table.consumer] })]);

export const complianceChecks = pgTable('compliance_checks', {
  id: uuid('id').defaultRandom().primaryKey(),
  correlationId: uuid('correlation_id').notNull(),
  wallet: text('wallet').notNull(),
  assetAddress: text('asset_address').notNull(),
  cviActive: boolean('cvi_active').notNull(),
  tier: integer('tier'),
  verificationCode: integer('verification_code'),
  assetIssued: boolean('asset_issued').notNull(),
  assetPaused: boolean('asset_paused').notNull(),
  poolEligible: boolean('pool_eligible'),
  rawResult: jsonb('raw_result').$type<Record<string, unknown>>(),
  checkedAt: timestamp('checked_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  index('compliance_wallet_asset_idx').on(table.wallet, table.assetAddress),
  index('compliance_correlation_idx').on(table.correlationId),
]);

export const valuationSnapshots = pgTable('valuation_snapshots', {
  id: uuid('id').defaultRandom().primaryKey(),
  assetAddress: text('asset_address').notNull(),
  valueMinor: numeric('value_minor', { precision: 78, scale: 0 }).notNull(),
  currency: text('currency').notNull(),
  source: text('source').notNull(),
  evidenceHash: text('evidence_hash').notNull(),
  signer: text('signer').notNull(),
  signature: text('signature').notNull(),
  validUntil: timestamp('valid_until', { withTimezone: true }).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [index('valuation_asset_idx').on(table.assetAddress)]);

export const documentRecords = pgTable('document_records', {
  id: uuid('id').defaultRandom().primaryKey(),
  assetAddress: text('asset_address').notNull(),
  objectKey: text('object_key').notNull(),
  contentHash: text('content_hash').notNull(),
  encryptedDataKey: text('encrypted_data_key').notNull(),
  mimeType: text('mime_type').notNull(),
  uploadedBy: text('uploaded_by').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [uniqueIndex('documents_object_key_uidx').on(table.objectKey)]);

export const auditLogs = pgTable('audit_logs', {
  id: uuid('id').defaultRandom().primaryKey(),
  correlationId: uuid('correlation_id').notNull(),
  actor: text('actor'),
  action: text('action').notNull(),
  resourceType: text('resource_type').notNull(),
  resourceId: text('resource_id'),
  outcome: text('outcome').notNull(),
  metadata: jsonb('metadata').$type<Record<string, unknown>>().notNull().default({}),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  index('audit_correlation_idx').on(table.correlationId),
  index('audit_actor_idx').on(table.actor),
]);

// Versioned protocol contracts are indexed independently. V1 remains represented by
// the original `repos` projection and can be backfilled into this registry later.
export const protocolDeployments = pgTable('protocol_deployments', {
  id: uuid('id').defaultRandom().primaryKey(),
  chainId: integer('chain_id').notNull(),
  protocolVersion: text('protocol_version').notNull(),
  module: text('module').notNull(),
  address: text('address').notNull(),
  deploymentBlock: bigint('deployment_block', { mode: 'bigint' }).notNull(),
  abiHash: text('abi_hash'),
  enabled: boolean('enabled').notNull().default(true),
  metadata: jsonb('metadata').$type<Record<string, unknown>>().notNull().default({}),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  uniqueIndex('protocol_deployments_chain_address_uidx').on(table.chainId, table.address),
  index('protocol_deployments_module_idx').on(table.chainId, table.protocolVersion, table.module),
]);

export const v2Offers = pgTable('v2_offers', {
  id: uuid('id').defaultRandom().primaryKey(),
  chainId: integer('chain_id').notNull(),
  marketAddress: text('market_address').notNull(),
  offerId: numeric('offer_id', { precision: 78, scale: 0 }).notNull(),
  seller: text('seller').notNull(),
  permittedBuyer: text('permitted_buyer'),
  assetAddress: text('asset_address').notNull(),
  settlementToken: text('settlement_token').notNull(),
  totalCollateral: numeric('total_collateral', { precision: 78, scale: 0 }).notNull(),
  remainingCollateral: numeric('remaining_collateral', { precision: 78, scale: 0 }).notNull(),
  targetPrincipal: numeric('target_principal', { precision: 78, scale: 0 }).notNull(),
  remainingPrincipal: numeric('remaining_principal', { precision: 78, scale: 0 }).notNull(),
  minimumFill: numeric('minimum_fill', { precision: 78, scale: 0 }).notNull(),
  cumulativeFee: numeric('cumulative_fee', { precision: 78, scale: 0 }).notNull().default('0'),
  annualRateBps: integer('annual_rate_bps').notNull(),
  defaultRateBps: integer('default_rate_bps').notNull(),
  durationSeconds: integer('duration_seconds').notNull(),
  offerExpiry: timestamp('offer_expiry', { withTimezone: true }).notNull(),
  gracePeriodSeconds: integer('grace_period_seconds').notNull(),
  earlyRepurchaseEnabled: boolean('early_repurchase_enabled').notNull().default(false),
  minimumHoldSeconds: integer('minimum_hold_seconds').notNull().default(0),
  breakFeeBps: integer('break_fee_bps').notNull().default(0),
  valuationId: numeric('valuation_id', { precision: 78, scale: 0 }),
  valuationHash: text('valuation_hash'),
  status: v2OfferStatus('status').notNull(),
  createTxHash: text('create_tx_hash').notNull(),
  lastTxHash: text('last_tx_hash').notNull(),
  lastBlockNumber: bigint('last_block_number', { mode: 'bigint' }).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  closedAt: timestamp('closed_at', { withTimezone: true }),
}, (table) => [
  uniqueIndex('v2_offers_chain_market_offer_uidx').on(table.chainId, table.marketAddress, table.offerId),
  index('v2_offers_market_status_expiry_idx').on(table.chainId, table.marketAddress, table.status, table.offerExpiry),
  index('v2_offers_seller_idx').on(table.seller),
  index('v2_offers_asset_idx').on(table.assetAddress),
]);

export const v2Positions = pgTable('v2_positions', {
  id: uuid('id').defaultRandom().primaryKey(),
  chainId: integer('chain_id').notNull(),
  marketAddress: text('market_address').notNull(),
  positionId: numeric('position_id', { precision: 78, scale: 0 }).notNull(),
  offerId: numeric('offer_id', { precision: 78, scale: 0 }).notNull(),
  auctionId: numeric('auction_id', { precision: 78, scale: 0 }),
  seller: text('seller').notNull(),
  buyer: text('buyer').notNull(),
  assetAddress: text('asset_address').notNull(),
  settlementToken: text('settlement_token').notNull(),
  principal: numeric('principal', { precision: 78, scale: 0 }).notNull(),
  collateral: numeric('collateral', { precision: 78, scale: 0 }).notNull(),
  openingFee: numeric('opening_fee', { precision: 78, scale: 0 }).notNull().default('0'),
  annualRateBps: integer('annual_rate_bps').notNull(),
  defaultRateBps: integer('default_rate_bps').notNull(),
  liquidationFeeBps: integer('liquidation_fee_bps').notNull(),
  auctionStartBps: integer('auction_start_bps').notNull(),
  auctionFloorBps: integer('auction_floor_bps').notNull(),
  auctionDurationSeconds: integer('auction_duration_seconds').notNull(),
  maxOracleAgeSeconds: integer('max_oracle_age_seconds').notNull(),
  staleOracleFallbackDelaySeconds: integer('stale_oracle_fallback_delay_seconds').notNull(),
  openingValuationDigest: text('opening_valuation_digest').notNull(),
  acceptedAt: timestamp('accepted_at', { withTimezone: true }).notNull(),
  maturityAt: timestamp('maturity_at', { withTimezone: true }).notNull(),
  repaymentDeadline: timestamp('repayment_deadline', { withTimezone: true }).notNull(),
  debtFrozenAt: timestamp('debt_frozen_at', { withTimezone: true }),
  frozenDebt: numeric('frozen_debt', { precision: 78, scale: 0 }),
  defaultValuationDigest: text('default_valuation_digest'),
  payoffAmount: numeric('payoff_amount', { precision: 78, scale: 0 }),
  status: v2PositionStatus('status').notNull(),
  lastTxHash: text('last_tx_hash').notNull(),
  lastBlockNumber: bigint('last_block_number', { mode: 'bigint' }).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  closedAt: timestamp('closed_at', { withTimezone: true }),
}, (table) => [
  uniqueIndex('v2_positions_chain_market_position_uidx').on(table.chainId, table.marketAddress, table.positionId),
  index('v2_positions_offer_idx').on(table.chainId, table.marketAddress, table.offerId),
  index('v2_positions_status_deadline_idx').on(table.status, table.repaymentDeadline),
  index('v2_positions_seller_idx').on(table.seller),
  index('v2_positions_buyer_idx').on(table.buyer),
]);

export const vaultBalances = pgTable('vault_balances', {
  chainId: integer('chain_id').notNull(),
  vaultAddress: text('vault_address').notNull(),
  account: text('account').notNull(),
  assetAddress: text('asset_address').notNull(),
  bucket: vaultBucket('bucket').notNull(),
  amount: numeric('amount', { precision: 78, scale: 0 }).notNull().default('0'),
  lastBlockNumber: bigint('last_block_number', { mode: 'bigint' }).notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  primaryKey({ columns: [table.chainId, table.vaultAddress, table.account, table.assetAddress, table.bucket] }),
  index('vault_balances_account_idx').on(table.account, table.assetAddress),
]);

export const vaultLedgerEntries = pgTable('vault_ledger_entries', {
  id: uuid('id').defaultRandom().primaryKey(),
  chainId: integer('chain_id').notNull(),
  vaultAddress: text('vault_address').notNull(),
  account: text('account').notNull(),
  assetAddress: text('asset_address').notNull(),
  bucket: vaultBucket('bucket').notNull(),
  delta: numeric('delta', { precision: 78, scale: 0 }).notNull(),
  balanceAfter: numeric('balance_after', { precision: 78, scale: 0 }).notNull(),
  referenceType: text('reference_type').notNull(),
  referenceId: numeric('reference_id', { precision: 78, scale: 0 }),
  reason: text('reason').notNull(),
  txHash: text('tx_hash').notNull(),
  logIndex: integer('log_index').notNull(),
  blockNumber: bigint('block_number', { mode: 'bigint' }).notNull(),
  occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull(),
}, (table) => [
  uniqueIndex('vault_ledger_event_uidx').on(table.chainId, table.txHash, table.logIndex, table.bucket),
  index('vault_ledger_account_idx').on(table.account, table.assetAddress, table.blockNumber),
  index('vault_ledger_reference_idx').on(table.referenceType, table.referenceId),
]);

export const oracleValuations = pgTable('oracle_valuations', {
  id: uuid('id').defaultRandom().primaryKey(),
  chainId: integer('chain_id').notNull(),
  oracleAddress: text('oracle_address').notNull(),
  valuationId: numeric('valuation_id', { precision: 78, scale: 0 }).notNull(),
  assetAddress: text('asset_address').notNull(),
  valueMinor: numeric('value_minor', { precision: 78, scale: 0 }).notNull(),
  priceE18: numeric('price_e18', { precision: 78, scale: 0 }).notNull(),
  currency: text('currency').notNull(),
  settlementToken: text('settlement_token').notNull(),
  nonce: numeric('nonce', { precision: 78, scale: 0 }).notNull(),
  validFrom: timestamp('valid_from', { withTimezone: true }).notNull(),
  observedAt: timestamp('observed_at', { withTimezone: true }).notNull(),
  validUntil: timestamp('valid_until', { withTimezone: true }).notNull(),
  evidenceHash: text('evidence_hash').notNull(),
  digest: text('digest').notNull(),
  signatures: jsonb('signatures').$type<Array<{ signer: string; signature: string }>>().notNull().default([]),
  invalidated: boolean('invalidated').notNull().default(false),
  txHash: text('tx_hash').notNull(),
  blockNumber: bigint('block_number', { mode: 'bigint' }).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  uniqueIndex('oracle_valuations_chain_oracle_id_uidx').on(table.chainId, table.oracleAddress, table.valuationId),
  uniqueIndex('oracle_valuations_chain_asset_nonce_uidx').on(table.chainId, table.assetAddress, table.nonce),
  index('oracle_valuations_asset_validity_idx').on(table.assetAddress, table.validUntil),
]);

export const riskConfigurations = pgTable('risk_configurations', {
  id: uuid('id').defaultRandom().primaryKey(),
  chainId: integer('chain_id').notNull(),
  riskManagerAddress: text('risk_manager_address').notNull(),
  assetAddress: text('asset_address').notNull(),
  configVersion: numeric('config_version', { precision: 78, scale: 0 }).notNull(),
  initialLtvBps: integer('initial_ltv_bps').notNull(),
  maintenanceLtvBps: integer('maintenance_ltv_bps').notNull(),
  liquidationLtvBps: integer('liquidation_ltv_bps').notNull(),
  auctionStartBps: integer('auction_start_bps').notNull(),
  auctionFloorBps: integer('auction_floor_bps').notNull(),
  liquidationFeeBps: integer('liquidation_fee_bps').notNull(),
  earlyMinHoldBps: integer('early_min_hold_bps').notNull(),
  earlyBreakFeeBps: integer('early_break_fee_bps').notNull(),
  defaultSpreadBps: integer('default_spread_bps').notNull(),
  maxDefaultRateBps: integer('max_default_rate_bps').notNull(),
  oracleMaxAgeSeconds: integer('oracle_max_age_seconds').notNull(),
  auctionDurationSeconds: integer('auction_duration_seconds').notNull(),
  marginCallSeconds: integer('margin_call_seconds').notNull(),
  staleOracleFallbackDelaySeconds: integer('stale_oracle_fallback_delay_seconds').notNull(),
  enabled: boolean('enabled').notNull().default(true),
  txHash: text('tx_hash').notNull(),
  blockNumber: bigint('block_number', { mode: 'bigint' }).notNull(),
  activatedAt: timestamp('activated_at', { withTimezone: true }).notNull(),
}, (table) => [
  uniqueIndex('risk_config_chain_manager_asset_version_uidx').on(table.chainId, table.riskManagerAddress, table.assetAddress, table.configVersion),
  index('risk_config_asset_active_idx').on(table.assetAddress, table.enabled),
]);

export const auctions = pgTable('auctions', {
  id: uuid('id').defaultRandom().primaryKey(),
  chainId: integer('chain_id').notNull(),
  auctionAddress: text('auction_address').notNull(),
  auctionId: numeric('auction_id', { precision: 78, scale: 0 }).notNull(),
  marketAddress: text('market_address').notNull(),
  positionId: numeric('position_id', { precision: 78, scale: 0 }),
  marginAccountId: numeric('margin_account_id', { precision: 78, scale: 0 }),
  seller: text('seller').notNull(),
  lender: text('lender'),
  assetAddress: text('asset_address').notNull(),
  settlementToken: text('settlement_token').notNull(),
  collateralAmount: numeric('collateral_amount', { precision: 78, scale: 0 }).notNull(),
  frozenDebt: numeric('frozen_debt', { precision: 78, scale: 0 }).notNull(),
  liquidationFeeBps: integer('liquidation_fee_bps').notNull(),
  valuationId: numeric('valuation_id', { precision: 78, scale: 0 }),
  valuationDigest: text('valuation_digest'),
  startPrice: numeric('start_price', { precision: 78, scale: 0 }).notNull(),
  floorPrice: numeric('floor_price', { precision: 78, scale: 0 }).notNull(),
  startsAt: timestamp('starts_at', { withTimezone: true }).notNull(),
  endsAt: timestamp('ends_at', { withTimezone: true }).notNull(),
  status: auctionStatus('status').notNull(),
  buyer: text('buyer'),
  clearingPrice: numeric('clearing_price', { precision: 78, scale: 0 }),
  lastTxHash: text('last_tx_hash').notNull(),
  lastBlockNumber: bigint('last_block_number', { mode: 'bigint' }).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  closedAt: timestamp('closed_at', { withTimezone: true }),
}, (table) => [
  uniqueIndex('auctions_chain_contract_id_uidx').on(table.chainId, table.auctionAddress, table.auctionId),
  index('auctions_status_end_idx').on(table.status, table.endsAt),
  index('auctions_position_idx').on(table.chainId, table.marketAddress, table.positionId),
]);

export const auctionSettlements = pgTable('auction_settlements', {
  id: uuid('id').defaultRandom().primaryKey(),
  chainId: integer('chain_id').notNull(),
  auctionAddress: text('auction_address').notNull(),
  auctionId: numeric('auction_id', { precision: 78, scale: 0 }).notNull(),
  buyer: text('buyer').notNull(),
  grossProceeds: numeric('gross_proceeds', { precision: 78, scale: 0 }).notNull(),
  lenderProceeds: numeric('lender_proceeds', { precision: 78, scale: 0 }).notNull(),
  protocolCost: numeric('protocol_cost', { precision: 78, scale: 0 }).notNull(),
  sellerSurplus: numeric('seller_surplus', { precision: 78, scale: 0 }).notNull(),
  lenderShortfall: numeric('lender_shortfall', { precision: 78, scale: 0 }).notNull(),
  txHash: text('tx_hash').notNull(),
  blockNumber: bigint('block_number', { mode: 'bigint' }).notNull(),
  settledAt: timestamp('settled_at', { withTimezone: true }).notNull(),
}, (table) => [uniqueIndex('auction_settlements_chain_auction_uidx').on(table.chainId, table.auctionAddress, table.auctionId)]);

export const settlementClaims = pgTable('settlement_claims', {
  id: uuid('id').defaultRandom().primaryKey(),
  chainId: integer('chain_id').notNull(),
  escrowAddress: text('escrow_address').notNull(),
  claimId: numeric('claim_id', { precision: 78, scale: 0 }).notNull(),
  beneficiary: text('beneficiary').notNull(),
  tokenAddress: text('token_address').notNull(),
  amount: numeric('amount', { precision: 78, scale: 0 }).notNull(),
  remaining: numeric('remaining', { precision: 78, scale: 0 }).notNull(),
  sourceType: text('source_type').notNull(),
  sourceId: numeric('source_id', { precision: 78, scale: 0 }),
  claimReference: text('claim_reference').notNull(),
  status: claimStatus('status').notNull(),
  createTxHash: text('create_tx_hash').notNull(),
  claimTxHash: text('claim_tx_hash'),
  lastBlockNumber: bigint('last_block_number', { mode: 'bigint' }).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  claimedAt: timestamp('claimed_at', { withTimezone: true }),
}, (table) => [
  uniqueIndex('settlement_claims_chain_escrow_id_uidx').on(table.chainId, table.escrowAddress, table.claimId),
  index('settlement_claims_beneficiary_status_idx').on(table.beneficiary, table.status),
]);

export const v2ComplianceDecisions = pgTable('v2_compliance_decisions', {
  id: uuid('id').defaultRandom().primaryKey(),
  correlationId: uuid('correlation_id').notNull(),
  chainId: integer('chain_id').notNull(),
  action: text('action').notNull(),
  role: text('role').notNull(),
  policyPool: text('policy_pool').notNull(),
  tokenAddress: text('token_address').notNull(),
  wallet: text('wallet').notNull(),
  transferFrom: text('transfer_from').notNull(),
  transferTo: text('transfer_to').notNull(),
  transferAmount: numeric('transfer_amount', { precision: 78, scale: 0 }).notNull(),
  resourceType: text('resource_type').notNull(),
  resourceId: text('resource_id'),
  decision: text('decision').notNull(),
  verificationCode: integer('verification_code'),
  cviActive: boolean('cvi_active').notNull(),
  assetIssued: boolean('asset_issued').notNull(),
  assetPaused: boolean('asset_paused').notNull(),
  poolEligible: boolean('pool_eligible'),
  ruleSnapshot: jsonb('rule_snapshot').$type<Record<string, unknown>>().notNull().default({}),
  rawResult: jsonb('raw_result').$type<Record<string, unknown>>(),
  checkedAt: timestamp('checked_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  index('v2_compliance_correlation_idx').on(table.correlationId),
  index('v2_compliance_resource_idx').on(table.resourceType, table.resourceId),
  index('v2_compliance_wallet_token_idx').on(table.wallet, table.tokenAddress, table.checkedAt),
]);

export const marginAccounts = pgTable('margin_accounts', {
  id: uuid('id').defaultRandom().primaryKey(),
  chainId: integer('chain_id').notNull(),
  marginEngineAddress: text('margin_engine_address').notNull(),
  accountId: numeric('account_id', { precision: 78, scale: 0 }).notNull(),
  owner: text('owner').notNull(),
  assetAddress: text('asset_address').notNull(),
  settlementToken: text('settlement_token').notNull(),
  rulesHash: text('rules_hash').notNull(),
  collateralAmount: numeric('collateral_amount', { precision: 78, scale: 0 }).notNull().default('0'),
  permittedLender: text('permitted_lender'),
  fundingTarget: numeric('funding_target', { precision: 78, scale: 0 }).notNull().default('0'),
  minimumFunding: numeric('minimum_funding', { precision: 78, scale: 0 }).notNull().default('0'),
  fundingDurationSeconds: integer('funding_duration_seconds').notNull().default(0),
  fundingExpiry: timestamp('funding_expiry', { withTimezone: true }),
  maxAnnualRateBps: integer('max_annual_rate_bps').notNull().default(0),
  fundingClosed: boolean('funding_closed').notNull().default(false),
  totalFunded: numeric('total_funded', { precision: 78, scale: 0 }).notNull().default('0'),
  totalDebt: numeric('total_debt', { precision: 78, scale: 0 }).notNull().default('0'),
  feeCharged: numeric('fee_charged', { precision: 78, scale: 0 }).notNull().default('0'),
  frozenDebt: numeric('frozen_debt', { precision: 78, scale: 0 }).notNull().default('0'),
  liquidationProceeds: numeric('liquidation_proceeds', { precision: 78, scale: 0 }).notNull().default('0'),
  remainingProceeds: numeric('remaining_proceeds', { precision: 78, scale: 0 }).notNull().default('0'),
  remainingCollateral: numeric('remaining_collateral', { precision: 78, scale: 0 }).notNull().default('0'),
  marginCallDeadline: timestamp('margin_call_deadline', { withTimezone: true }),
  defaultDeclaredAt: timestamp('default_declared_at', { withTimezone: true }),
  maxOracleAgeSeconds: integer('max_oracle_age_seconds').notNull().default(0),
  auctionDurationSeconds: integer('auction_duration_seconds').notNull().default(0),
  marginCallPeriodSeconds: integer('margin_call_period_seconds').notNull().default(0),
  staleOracleFallbackDelaySeconds: integer('stale_oracle_fallback_delay_seconds').notNull().default(0),
  activeExposureCount: integer('active_exposure_count').notNull().default(0),
  unclaimedExposureCount: integer('unclaimed_exposure_count').notNull().default(0),
  initialLtvBps: integer('initial_ltv_bps').notNull().default(0),
  maintenanceLtvBps: integer('maintenance_ltv_bps').notNull().default(0),
  liquidationLtvBps: integer('liquidation_ltv_bps').notNull().default(0),
  auctionStartBps: integer('auction_start_bps').notNull().default(0),
  auctionFloorBps: integer('auction_floor_bps').notNull().default(0),
  liquidationFeeBps: integer('liquidation_fee_bps').notNull().default(0),
  paymentDefaultDeclared: boolean('payment_default_declared').notNull().default(false),
  inKindCloseout: boolean('in_kind_closeout').notNull().default(false),
  auctionId: numeric('auction_id', { precision: 78, scale: 0 }),
  claimPoolId: numeric('claim_pool_id', { precision: 78, scale: 0 }),
  closeoutValuationDigest: text('closeout_valuation_digest'),
  valuationId: numeric('valuation_id', { precision: 78, scale: 0 }),
  collateralValue: numeric('collateral_value', { precision: 78, scale: 0 }),
  ltvBps: integer('ltv_bps'),
  status: marginAccountStatus('status').notNull(),
  lastTxHash: text('last_tx_hash').notNull(),
  lastBlockNumber: bigint('last_block_number', { mode: 'bigint' }).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  closedAt: timestamp('closed_at', { withTimezone: true }),
}, (table) => [
  uniqueIndex('margin_accounts_chain_engine_id_uidx').on(table.chainId, table.marginEngineAddress, table.accountId),
  index('margin_accounts_owner_idx').on(table.owner),
  index('margin_accounts_status_idx').on(table.status),
  index('margin_accounts_fundable_idx').on(table.marginEngineAddress, table.fundingClosed, table.fundingExpiry),
]);

export const marginExposures = pgTable('margin_exposures', {
  id: uuid('id').defaultRandom().primaryKey(),
  chainId: integer('chain_id').notNull(),
  marginEngineAddress: text('margin_engine_address').notNull(),
  exposureId: numeric('exposure_id', { precision: 78, scale: 0 }).notNull(),
  accountId: numeric('account_id', { precision: 78, scale: 0 }).notNull(),
  lender: text('lender').notNull(),
  principal: numeric('principal', { precision: 78, scale: 0 }).notNull(),
  accruedDebt: numeric('accrued_debt', { precision: 78, scale: 0 }).notNull(),
  openingFee: numeric('opening_fee', { precision: 78, scale: 0 }).notNull().default('0'),
  annualRateBps: integer('annual_rate_bps').notNull(),
  openedAt: timestamp('opened_at', { withTimezone: true }).notNull(),
  maturityAt: timestamp('maturity_at', { withTimezone: true }).notNull(),
  settlementClaimId: numeric('settlement_claim_id', { precision: 78, scale: 0 }),
  liquidationClaimAmount: numeric('liquidation_claim_amount', { precision: 78, scale: 0 }),
  status: text('status').notNull(),
  lastTxHash: text('last_tx_hash').notNull(),
  lastBlockNumber: bigint('last_block_number', { mode: 'bigint' }).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  uniqueIndex('margin_exposures_chain_engine_id_uidx').on(table.chainId, table.marginEngineAddress, table.exposureId),
  index('margin_exposures_account_idx').on(table.chainId, table.marginEngineAddress, table.accountId),
  index('margin_exposures_lender_idx').on(table.lender),
]);

export const marginCalls = pgTable('margin_calls', {
  id: uuid('id').defaultRandom().primaryKey(),
  chainId: integer('chain_id').notNull(),
  marginEngineAddress: text('margin_engine_address').notNull(),
  callId: numeric('call_id', { precision: 78, scale: 0 }).notNull(),
  accountId: numeric('account_id', { precision: 78, scale: 0 }).notNull(),
  openedLtvBps: integer('opened_ltv_bps').notNull(),
  cureDeadline: timestamp('cure_deadline', { withTimezone: true }).notNull(),
  status: text('status').notNull(),
  openedTxHash: text('opened_tx_hash').notNull(),
  resolvedTxHash: text('resolved_tx_hash'),
  lastBlockNumber: bigint('last_block_number', { mode: 'bigint' }).notNull(),
  openedAt: timestamp('opened_at', { withTimezone: true }).notNull(),
  resolvedAt: timestamp('resolved_at', { withTimezone: true }),
}, (table) => [
  uniqueIndex('margin_calls_chain_engine_id_uidx').on(table.chainId, table.marginEngineAddress, table.callId),
  index('margin_calls_status_deadline_idx').on(table.status, table.cureDeadline),
]);

export const marginLiquidations = pgTable('margin_liquidations', {
  id: uuid('id').defaultRandom().primaryKey(),
  chainId: integer('chain_id').notNull(),
  marginEngineAddress: text('margin_engine_address').notNull(),
  liquidationId: numeric('liquidation_id', { precision: 78, scale: 0 }).notNull(),
  accountId: numeric('account_id', { precision: 78, scale: 0 }).notNull(),
  auctionId: numeric('auction_id', { precision: 78, scale: 0 }).notNull(),
  frozenDebt: numeric('frozen_debt', { precision: 78, scale: 0 }).notNull(),
  collateralAmount: numeric('collateral_amount', { precision: 78, scale: 0 }).notNull(),
  totalProceeds: numeric('total_proceeds', { precision: 78, scale: 0 }),
  proceedsPerDebtRay: numeric('proceeds_per_debt_ray', { precision: 78, scale: 0 }),
  status: text('status').notNull(),
  startTxHash: text('start_tx_hash').notNull(),
  settleTxHash: text('settle_tx_hash'),
  lastBlockNumber: bigint('last_block_number', { mode: 'bigint' }).notNull(),
  startedAt: timestamp('started_at', { withTimezone: true }).notNull(),
  settledAt: timestamp('settled_at', { withTimezone: true }),
}, (table) => [
  uniqueIndex('margin_liquidations_chain_engine_id_uidx').on(table.chainId, table.marginEngineAddress, table.liquidationId),
  index('margin_liquidations_account_idx').on(table.chainId, table.marginEngineAddress, table.accountId),
]);

export const automationJobs = pgTable('automation_jobs', {
  id: uuid('id').defaultRandom().primaryKey(),
  chainId: integer('chain_id').notNull(),
  contractAddress: text('contract_address').notNull(),
  action: text('action').notNull(),
  resourceType: text('resource_type').notNull(),
  resourceId: numeric('resource_id', { precision: 78, scale: 0 }).notNull(),
  scheduledFor: timestamp('scheduled_for', { withTimezone: true }).notNull(),
  status: automationJobStatus('status').notNull().default('PENDING'),
  attempts: integer('attempts').notNull().default(0),
  maxAttempts: integer('max_attempts').notNull().default(12),
  nextAttemptAt: timestamp('next_attempt_at', { withTimezone: true }).notNull(),
  lockedBy: text('locked_by'),
  lockedAt: timestamp('locked_at', { withTimezone: true }),
  preparedAt: timestamp('prepared_at', { withTimezone: true }),
  submittedAt: timestamp('submitted_at', { withTimezone: true }),
  txHash: text('tx_hash'),
  transactionNonce: numeric('transaction_nonce', { precision: 78, scale: 0 }),
  signedTransaction: text('signed_transaction'),
  lastError: text('last_error'),
  metadata: jsonb('metadata').$type<Record<string, unknown>>().notNull().default({}),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  completedAt: timestamp('completed_at', { withTimezone: true }),
}, (table) => [
  uniqueIndex('automation_jobs_resource_action_uidx').on(table.chainId, table.contractAddress, table.action, table.resourceType, table.resourceId),
  index('automation_jobs_due_idx').on(table.status, table.nextAttemptAt),
]);
